yakbak/views.py
import logging

from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    url_for,
)
from flask_login import login_required, login_user, logout_user
from sqlalchemy.exc import IntegrityError
from werkzeug.wrappers import Response

from yakbak import mail
from yakbak.auth import get_magic_link_token_and_expiry, parse_magic_link_token
from yakbak.forms import (
    DemographicSurveyForm,
    EmailAddressForm,
    SpeakerEmailForm,
    TalkForm,
    UserForm,
)
from yakbak.models import (
    db,
    DemographicSurvey,
    InvitationStatus,
    Talk,
    TalkSpeaker,
    TalkStatus,
    UsedMagicLink,
    User,
)


app = Blueprint("views", __name__)
logger = logging.getLogger("views")


def load_talk(talk_id: int) -> Talk:
    talk = Talk.query.get_or_404(talk_id)
    if g.user not in [s.user for s in talk.speakers]:
        # TODO: figure out how to do this in the query directly?
        abort(404)

    return talk


@app.route("/")
def index() -> Response:
    return render_template("index.html")


@app.route("/login")
def login() -> Response:
    auth_methods = current_app.settings.auth.auth_methods()
    return render_template("login.html", auth_methods=auth_methods)


@app.route("/logout")
def logout() -> Response:
    logout_user()
    return redirect(url_for("views.index"))


@app.route("/login/email", methods=["GET", "POST"])
def email_magic_link() -> Response:
    form = EmailAddressForm()
    if form.validate_on_submit():
        token, expiry = get_magic_link_token_and_expiry(form.email.data)
        url = url_for(
            "views.email_magic_link_login",
            magic_link_token=token,
            _external=True,
        )
        mail.send_mail(
            to=[form.email.data],
            template="email/magic-link",
            magic_link=url,
            magic_link_expiration=expiry,
        )
        return redirect(url_for("views.email_magic_link_done"))
    return render_template("email_magic_link.html", form=form)


@app.route("/login/email/sent")
def email_magic_link_done() -> Response:
    return render_template("email_magic_link_sent.html")


@app.route("/login/token/<magic_link_token>")
def email_magic_link_login(magic_link_token: str) -> Response:
    try:
        used_magic_link = UsedMagicLink(token=magic_link_token)
        db.session.add(used_magic_link)
        db.session.commit()
    except IntegrityError:
        # race condition, UsedMagicLink row exists
        db.session.rollback()
        return current_app.response_class(
            render_template("email_magic_link_used.html"),
            status=401,
        )

    verified_email = parse_magic_link_token(magic_link_token)
    if verified_email is None:
        abort(404)

    user = User.query.filter_by(email=verified_email).first()
    if user:
        login_user(user)
        return redirect(url_for("views.talks_list"))

    user = User(email=verified_email, fullname=verified_email)
    db.session.add(user)
    db.session.commit()
    login_user(user)
    flash("Welcome! Please tell us your name.")
    return redirect(url_for("views.user_profile"))


@app.route("/profile", methods=["GET", "POST"])
@login_required
def user_profile() -> Response:
    user = g.user
    form = UserForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("views.index"))

    return render_template("profile.html", form=form)


@app.route("/talks")
@login_required
def talks_list() -> Response:
    talks = [
        ts.talk for ts in g.user.talks
        if ts.state == InvitationStatus.CONFIRMED
    ]
    proposed_talks = [t for t in talks if t.state == TalkStatus.PROPOSED]
    withdrawn_talks = [t for t in talks if t.state == TalkStatus.WITHDRAWN]

    invitations = TalkSpeaker.query.filter(
        TalkSpeaker.user == g.user,
        TalkSpeaker.state != InvitationStatus.CONFIRMED,
        TalkSpeaker.state != InvitationStatus.DELETED,
    ).all()
    speaker_actions = {
        InvitationStatus.PENDING: [
            ("Reject", "danger", "views.reject_invite"),
            ("Accept", "primary", "views.accept_invite"),
        ],
        InvitationStatus.REJECTED: [
            ("Accept", "primary", "views.accept_invite"),
        ],
    }
    talk_actions = {
        TalkStatus.PROPOSED: [
            ("Withdraw", "danger", "views.withdraw_proposal"),
        ],
        TalkStatus.WITHDRAWN: [
            ("Re-Submit", "primary", "views.resubmit_proposal"),
        ],
    }
    prompt_for_survey = proposed_talks and not g.user.demographic_survey
    prompt_for_bio = proposed_talks and not g.user.speaker_bio
    return render_template(
        "talks_list.html",
        proposed_talks=proposed_talks,
        withdrawn_talks=withdrawn_talks,
        num_talks=len(proposed_talks),
        invitations=invitations,
        speaker_actions=speaker_actions,
        talk_actions=talk_actions,
        prompt_for_survey=prompt_for_survey,
        prompt_for_bio=prompt_for_bio,
        TalkStatus=TalkStatus,
    )


@app.route("/talks/<int:talk_id>", methods=["GET", "POST"])
@login_required
def edit_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    form = TalkForm(conference=g.conference, obj=talk)
    if form.validate_on_submit():
        form.populate_obj(talk)
        talk.reset_after_edits()
        db.session.add(talk)
        db.session.commit()
        return redirect(url_for("views.preview_talk", talk_id=talk.talk_id))

    return render_template("edit_talk.html", talk=talk, form=form)


@app.route("/talks/<int:talk_id>/anonymized", methods=["GET", "POST"])
@login_required
def anonymized_talk(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    if not talk.is_anonymized:
        flash("This talk has not yet been anonymized for review")

    return render_template("anonymized_talk_preview.html", talk=talk)


@app.route("/talks/<int:talk_id>/withdraw")
@login_required
def withdraw_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.WITHDRAWN
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} withdrawn")
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/resubmit")
@login_required
def resubmit_proposal(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    talk.state = TalkStatus.PROPOSED
    db.session.add(talk)
    db.session.commit()
    flash(f"{talk.title!r} re-submitted")
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/speakers", methods=["GET", "POST"])
@login_required
def edit_speakers(talk_id: int) -> Response:
    talk = load_talk(talk_id)
    actions = {
        InvitationStatus.PENDING: [("Uninvite", "danger", "views.uninvite_speaker")],
        InvitationStatus.CONFIRMED: [],
        InvitationStatus.REJECTED: [],
        InvitationStatus.DELETED: [("Reinvite", "primary", "views.reinvite_speaker")],
    }

    speaker_emails = [s.user.email for s in talk.speakers]
    form = SpeakerEmailForm(speaker_emails)
    if form.validate_on_submit():
        email = form.email.data
        try:
            user = User(fullname=email, email=email)
            db.session.add(user)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()
            user = User.query.filter_by(email=email).one()

        try:
            talk.add_speaker(user, InvitationStatus.PENDING)
            db.session.commit()
        except IntegrityError:
            db.session.rollback()

        mail.send_mail(
            to=[email],
            template="email/speaker-invite",
            talk=talk,
        )

        return redirect(url_for("views.edit_speakers", talk_id=talk.talk_id))

    return render_template(
        "edit_speakers.html",
        talk=talk,
        actions=actions,
        form=form,
    )


@app.route("/talks/<int:talk_id>/speakers/uninvite/<int:user_id>")
@login_required
def uninvite_speaker(talk_id: int, user_id: int) -> Response:
    talk = load_talk(talk_id)
    user = User.query.get_or_404(user_id)

    ts = TalkSpeaker.query.filter_by(
        talk_id=talk.talk_id,
        user_id=user.user_id,
    ).one_or_none()
    if not ts:
        abort(404)

    ts.state = InvitationStatus.DELETED
    db.session.add(ts)
    db.session.commit()
    # TODO: send email?
    return redirect(url_for("views.edit_speakers", talk_id=talk.talk_id))


@app.route("/talks/<int:talk_id>/speakers/reinvite/<int:user_id>")
@login_required
def reinvite_speaker(talk_id: int, user_id: int) -> Response:
    talk = load_talk(talk_id)
    user = User.query.get_or_404(user_id)

    ts = TalkSpeaker.query.filter_by(
        talk_id=talk.talk_id,
        user_id=user.user_id,
    ).one_or_none()
    if not ts:
        abort(404)

    ts.state = InvitationStatus.PENDING
    db.session.add(ts)
    db.session.commit()
    # TODO: send email?
    return redirect(url_for("views.edit_speakers", talk_id=talk.talk_id))


@app.route("/talks/<int:talk_id>/speakers/accept")
@login_required
def accept_invite(talk_id: int) -> Response:
    ts = TalkSpeaker.query.filter(
        TalkSpeaker.talk_id == talk_id,
        TalkSpeaker.user == g.user,
    ).one_or_none()
    if not ts:
        abort(401)

    ts.state = InvitationStatus.CONFIRMED
    db.session.add(ts)
    db.session.commit()
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/speakers/reject")
@login_required
def reject_invite(talk_id: int) -> Response:
    ts = TalkSpeaker.query.filter(
        TalkSpeaker.talk_id == talk_id,
        TalkSpeaker.user == g.user,
    ).one_or_none()
    if not ts:
        abort(401)

    ts.state = InvitationStatus.REJECTED
    db.session.add(ts)
    db.session.commit()
    return redirect(url_for("views.talks_list"))


@app.route("/talks/<int:talk_id>/preview")
@login_required

yakbak/templates/anonymized_talk_preview.html
{% extends "base.html" %}

{% block title %}Anonymization of "{{ talk.title|default("Talk") }}" - {{ super() }}{% endblock %}

{% block morestyles %}
<style type="text/css">
pre {
  white-space: pre-wrap;       /* css-3 */
}
span.diff_add {
  background-color: #98FB98;
}
span.diff_sub {
  background-color: #F08080;
}
</style>
{% endblock %}

{% block container %}
{% if mode != "admin" %}
<div class="row">
  <div class="col">
    <div class="alert alert-warning" role="alert">
      <p>
      While previewing this proposal, we have identified some
      information that could be used by voters or the program
      committee to identify who you are. It's very important to
      us at {{ g.conference.informal_name }} to have a truly
      anonymous review process, so we have edited the version
      that will be seen by voters and reviewers to remove this
      identifying information.
      </p>
      <p>
      If you'd like, you may
      <a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">edit
      your proposal</a> to re-word and remove the identifying
      information. This will trigger re-review by
      {{ g.conference.informal_name }} staff.
      </p>
    </div>
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col">
    <h2>{{ talk|anonymization_diff("title") }}</h2>
  </div>
</div>
<div class="row">
  <div class="col">
    <pre>{{ talk|anonymization_diff("description") }}</pre>
  </div>
</div>
<div class="row">
  <div class="col">
    <h3>Outline</h3>
    <pre>{{ talk|anonymization_diff("outline") }}</pre>
  </div>
</div>
{% if mode == "admin" %}
<div class="row">
  <div class="col">
    <a class="btn btn-primary" href="{{ url_for("manage.anonymize_talks") }}">Anonymize Next Talk</a>
  </div>
</div>
{% endif %}
{% endblock %}

yakbak/templates/base.html
{# Modified from base.html in flask_bootstrap4 #}
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block metas %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {%- endblock metas %}

    {%- block head %}
    <title>{% block title %}{{ g.conference.informal_name }}{% endblock %}</title>
    <link rel="icon" href="{{ url_for("static", filename="favicon.png") }}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for("static", filename="site.css") }}">
    {% block morestyles %}
    {%- endblock morestyles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for("views.index") }}">{{ g.conference.informal_name }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% for label, url, active in left_nav %}
            <li class="nav-item{% if active %} active{% endif %}">
              <a class="nav-link" href="{{ url }}">{{ label }}{% if active %} <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            {% endfor %}
          </ul>
          <ul class="navbar-nav">
            {% for label, url, active in right_nav %}
            <li class="nav-item{% if active %} active{% endif %}">
              <a class="nav-link" href="{{ url }}">{{ label }}{% if active %} <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
    {%- endblock navbar %}

    {% block content %}
    {% set messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    <div class="container pt-3">
      {% for category, message in messages %}
      <div class="{%- if category == 'warning' -%}
      alert-warning
      {%- elif category == 'error' -%}
      alert-danger
      {%- else -%}
      alert-info
      {%- endif %} alert">
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %}

    <div class="main-container container pt-3">
      {% block container %}
      <div class="row">
        <div class="col">{% block main %}{% endblock %}</div>
      </div>
      {% endblock %}
    </div>
    {%- endblock content %}

    {% block footer %}
    <footer class="footer bg-light">
      <div class="container">
        <p>
        <small class="text-muted">
          Copyright &copy; 2019 Big Apple Py, Inc.
        </small>
        </p>
        <p>
        <small class="text-muted">
          Spot a problem? Email <a href="mailto:{{ g.conference.cfp_email }}">{{ g.conference.cfp_email }}</a>.
        </small>
        </p>
      </div>
    </footer>
    {% endblock footer %}

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% block morescripts %}
    {%- endblock morescripts %}
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

yakbak/templates/demographic_survey_done.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Demographic Survey - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-md-8">
    {% if optout %}
    <h1>You Have Opted Out of the PyGotham Demographic Survey</h1>
    <p>
    If you change your mind, you can always return here from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>
    </p>
    {% else %}
    <h1>Thanks For Completing the PyGotham Demographic Survey</h1>
    <p>
    You can always edit your responses from your
    <a href="{{ url_for("views.user_profile") }}">profile</a>.
    </p>
    {% endif %}
</div>
{% endblock %}

yakbak/templates/edit_speakers.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Speakers for {{ talk.title }} - {{ super() }}{% endblock %}

{% block container %}
<div class="row py-3">
  <div class="col">
    <h3>Speakers for {{ talk.title }}:</h3>
  </div>
</div>
{% for talk_speaker in talk.speakers %}
  {% set speaker = talk_speaker.user %}
  {% set state = talk_speaker.state %}
  <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %} speaker">
    <div class="col-md-7">{{ speaker.fullname }} ({{ speaker.email }})</div>
    <div class="col-md-3 text-right">{{ state.name|title }}</div>
    <div class="col-md-2 text-right">
      {% for label, cls, view in actions[state] %}
      <a href="{{ url_for(view, talk_id=talk.talk_id, user_id=speaker.user_id) }}" class="btn btn-outline-{{ cls }} btn-sm">{{ label }}</a>
      {% endfor %}
    </div>
  </div>
{% endfor %}
<form method="POST">
  <div class="row py-2">
    <div class="col-md-10">
      {{ macros.render_field(form.email, "user@example.com") }}
      {{ macros.render_error(form.email) }}
    </div>
    <div class="col-md-2 text-right">
      <button class="btn btn-primary btn-block" type="submit">Invite Speaker</a>
    </div>
  </div>
  {{ form["csrf_token"] }}
</form>
<div class="row">
  <div class="col text-right">
    <small><a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">Return to {{ talk.title }}</a></small>
  </div>
</div>
{% endblock %}

yakbak/templates/email_magic_link.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Request Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>You can log in using just your email address -- we'll send a link that
you can click which will return you to the site logged in and ready to go!</p>
<form method="post">
  <div class="form-group">
    {{ macros.render_label(form.email, "Email Address") }}
    {{ macros.render_field(form.email, "jane@example.com") }}
    {% if form.email.errors %}
    {{ macros.render_error(form.email) }}
    {% else %}
    <small class="form-text" id="email-help">If you are returning, be sure to use the same email address as last time</small>
    {% endif %}
  </div>
  <button type="submit" class="btn btn-primary">Send Magic Link</button>
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
</form>
{% endblock %}

yakbak/templates/email_magic_link_sent.html
{% extends "base.html" %}
{% import "macros.html" as macros %}

{% block title %}Request Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>We have sent a link to you, and it should be arriving soon. Once it does,
just click it to return here and log in!</p>
{% endblock %}

yakbak/templates/email_magic_link_used.html
{% extends "base.html" %}

{% block title %}Invalid Login Link - {{ super() }}{% endblock %}

{% block container %}
<p>
That magic link is invalid. You can <a href="{{ url_for("views.email_magic_link") }}">create another</a>
or <a href="{{ url_for("views.login") }}">choose another login method</a>.
</p>
{% endblock %}

yakbak/templates/login.html
{% extends "base.html" %}

{% block title %}Login - {{ super() }}{% endblock %}

{% block morestyles %}
<style type="text/css">
  a.card-link:hover, a.card-link:active {
    text-decoration: none;
  }
</style>
{% endblock %}

{% block container %}
<div class="row py-3">
  <div class="col">
    <h3>Log in with:</h3>
  </div>
</div>
<div class="row py-1">
  {% for auth in auth_methods %}
  <div class="col-md-4">
    <div class="card">
      <a href="{{ auth.url() }}" class="card-link text-body">
        <div class="card-body text-center">
          <img class="img-fluid" src="{{ url_for("static", filename="social/" +  auth.name + ".png") }}" alt="{{ auth.display_name }} logo">
          <h5 class="py-2">{{ auth.display_name }}</h5>
          <button class="btn btn-primary">Log In</button>
        </div>
      </a>
    </div>
  </div>
  {% if loop.cycle(False, False, True) and not loop.last -%}
  </div><div class="row py-1">
  {%- endif %}
  {% endfor %}
</div>
{% endblock %}

yakbak/templates/preview_talk.html
{% extends "base.html" %}

{% block title %}Preview "{{ talk.title|default("Talk") }}" - {{ super() }}{% endblock %}

{% block container %}
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col"><h1>{{ talk.title }}</h1></div>
      <div class="w-100"></div>
      <div class="col"><h4>{{ talk.length }} Minutes</h2></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <div class="row">
      <div class="col">
        {{ talk.description|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Outline:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.outline|markdown }}
      </div>
    </div>
    <div class="row border bg-light my-2 py-2">
      <div class="col"><h2>Audience Take-Aways:</h2></div>
      <div class="w-100"></div>
      <div class="col">
        {{ talk.take_aways|markdown }}
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <em class="text-muted">Reviewers will see voting instructions here.</em>
  </div>
</div>
<div class="row py-3">
  <div class="col">
    <a class="btn btn-primary" href="{{ url_for("views.talks_list") }}">Save &amp; Return</a> or
    <a class="btn btn-light border" href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">Edit Again</a>
  </div>
</div>
{% endblock %}

yakbak/templates/talks_list.html
{% extends "base.html" %}

{% block title %}Talks - {{ super() }}{% endblock %}

{% macro vitals(talk) %}
{% set speakers = talk.speakers|map(attribute="user") %}
{% set other_speakers = speakers|remove(user)|map(attribute="fullname")|list %}
{% if other_speakers|length > 1 %}
({{ talk.length }} Minutes, {{ other_speakers|join(", ") }}, and You)
{% elif other_speakers|length == 1 %}
({{ talk.length }} Minutes, {{ other_speakers|join("") }} and You)
{% else %}
({{ talk.length }} Minutes)
{% endif %}
{% endmacro %}

{% block container %}
{% if prompt_for_survey %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  In order to help us ensure a diverse and inclusive {{ g.conference.informal_name }},
  please consider filling out the <a href="{{ url_for("views.demographic_survey") }}">demographic
  survey</a>.</p>
  <p>You may <a href="{{ url_for("views.demographic_survey_opt_out") }}">opt
  out</a> to dismiss this message.</p>
</div>
{% endif %}
{% if prompt_for_bio %}
<div class="alert alert-info" role="alert">
  <p class="mt-3">Thanks for submitting {% if num_talks == 1 %}a talk{% else %}talks{% endif %}!
  Please add a <a href="{{ url_for("views.user_profile") }}">speaker biography</a> to your profile,
  for inclusion in the conference program.
  </p>
</div>
{% endif %}

{% macro talk_table(talks) %}
{% for talk in talks %}
  <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
    <div class="col-md-7 talk">
      <a href="{{ url_for("views.edit_talk", talk_id=talk.talk_id) }}">{{ talk.title|truncate(100) }}</a>
      {{ vitals(talk) }}
    </div>
    <div class="col-md-5 text-right">
      Updated {{ talk.updated|timesince }}
      <a href="{{ url_for("views.edit_speakers", talk_id=talk.talk_id) }}" class="btn btn-outline-primary btn-sm ml-2">Manage Speakers</a>
      {% for label, cls, view in talk_actions[talk.state] %}
      <a href="{{ url_for(view, talk_id=talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
      {% endfor %}
    </div>
    {% if talk.has_anonymization_changes %}
    <div class="col-md-12 mt-2">
      <div class="alert alert-warning my-0 pt-1 pb-2" role="alert">
        <small>
        This talk has anonymization changes. Please <a href="{{ url_for("views.anonymized_talk", talk_id=talk.talk_id) }}">review
        the anonymized version</a>, and consider updating your talk for
        anonymous review.
        </small>
      </div>
    </div>
    {% endif %}
  </div>
{% endfor %}
{% endmacro %}

{% set has_proposed_talks = proposed_talks|length > 0 %}
{% set has_withdrawn_talks = withdrawn_talks|length > 0 %}

<div class="row py-3">
  <div class="col">
    <h3>{% if has_withdrawn_talks %}Proposed {% endif %}Talks:</h3>
    {% if has_proposed_talks %}
    {{ talk_table(proposed_talks) }}
    {% else %}
    <div class="row py-2 border-top border-right border-left border-bottom">
      <div class="col-md-12">
        <em>No talks yet. Why not <a href="{{ url_for("views.create_talk") }}">add one now?</a></em>
      </div>
    </div>
    {% endif %}
  </div>
</div>
<div class="row py-2">
  <div class="col text-right">
    <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
  </div>
</div>
{% if has_withdrawn_talks %}
<div class="row py-3">
  <div class="col">
    <h3 class="my-3">Withdrawn Talks:</h3>
    <p><em>Withdrawn talks will not be considered for inclusion in {{ g.conference.informal_name }}.</em></p>
    {{ talk_table(withdrawn_talks) }}
  </div>
</div>
{% endif %}

{% if invitations|length > 0 %}
  <div class="row py-3">
    <div class="col">
      <h3>Speaker Invitations:</h3>
    </div>
  </div>
  {% for invitation in invitations %}
    <div class="row py-2 border-top border-right border-left{% if loop.last %} border-bottom{% endif %}">
      <div class="col-md-9 talk">
        {{ invitation.talk.title|truncate(100) }}
        {{ vitals(invitation.talk) }}
      </div>
      <div class="col-md-3 text-right">
        {% for label, cls, view in speaker_actions[invitation.state] %}
        <a href="{{ url_for(view, talk_id=invitation.talk.talk_id) }}" class="btn btn-outline-{{cls}} btn-sm">{{ label }}</a>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
  <div class="row py-2">
    <div class="col text-right">
      <a class="btn btn-primary" href="{{ url_for("views.create_talk") }}">Add Talk</a>
    </div>
  </div>
{% endif %}
{% endblock %}